name: moment
description: moment for Dart
version: 0.0.2
homepage: https://github.com/pd4d10/moment
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: ^0.15.7

dev_dependencies:
  test: ^1.0.0
